# Generated by Django 3.1.5 on 2021-04-17 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('type_desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_plate', models.CharField(max_length=20)),
                ('vehicle', models.ImageField(upload_to='')),
                ('km_driven', models.PositiveSmallIntegerField()),
                ('seat', models.PositiveSmallIntegerField()),
                ('price_per_day', models.CharField(max_length=100)),
                ('wheeler', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('is_available', models.CharField(default=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicletype')),
            ],
        ),
    ]
