# Generated by Django 3.1.5 on 2021-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
